runtime: nodejs20

handlers:
  - url: /assets
    static_dir: assets

  - url: /components
    static_dir: components

  - url: /script.js
    static_files: script.js
    upload: script.js

  - url: /myhistory.html
    static_files: myhistory.html
    upload: myhistory.html

  - url: /investment.html
    static_files: investment.html
    upload: investment.html

  - url: /services.html
    static_files: services.html
    upload: services.html

  - url: /portfolio.html
    static_files: portfolio.html
    upload: portfolio.html

  # NEW: Match /portfolio route without .html
  - url: /portfolio
    static_files: portfolio.html
    upload: portfolio.html

  - url: /
    static_files: index.html
    upload: index.html

  - url: /.*
    static_files: index.html
    upload: index.html

